package com.openclassrooms.realestatemanager.ui.creation

import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.openclassrooms.realestatemanager.db.RealEstateAdWithPhotoDAO
import com.openclassrooms.realestatemanager.model.RealEstateAdEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class RealEstateCreationViewModel(
    private val realEstateAdWithPhotoDAO: RealEstateAdWithPhotoDAO
) : ViewModel() {

    val liveDataCloseActivity = MutableLiveData<Unit>()

    fun createRealEstate(realEstateAdEntity: RealEstateAdEntity) {
        viewModelScope.launch(Dispatchers.IO) {
            // TODO Si besoin la primary key autogenerated se récupère comme ça
            val realEstateId = realEstateAdWithPhotoDAO.saveRealEstateAd(realEstateAdEntity)

            withContext(Dispatchers.Main) {
                liveDataCloseActivity.value = Unit
            }
        }
    }
}